SELECT DISTINCT
	NF.MANDT, 
	NF.BUKRS AS 'EMPRESA',
	NF.BRANCH AS 'LOCAL DE NEGOCIOS',
	LEFT(NF.BUKRS, 2) + RIGHT(NF.BRANCH, 2) AS 'CENTRO',
	NF.REGIO AS 'REGIAO',
	NF.PSTDAT AS 'DATA_LÇTO',
	NF.PARTYP AS 'TIPO_PARCEIRO', 
	NF.PARID AS 'ID_EXTERNO',
	NF.NAME1 AS 'CLIENTE',
	PED.VBELN AS 'PEDIDO',
	NF.DIRECT AS 'DIREÇAO',
	NF.NFENUM AS 'NUM_NF',
	NF.CANCEL AS 'ESTORNO', 
	NF.CRENAM AS 'USUARIO',
	VEND.BU_SORT2+' '+VEND.BU_SORT1 AS 'VENDEDOR',
	NF.NFTOT AS 'MONTANTE'	
FROM
	`production-servers-magnumtires.prdmgm_sap_cdc_processed.j_1bnfdoc` AS NF
INNER JOIN
	`production-servers-magnumtires.prdmgm_sap_cdc_processed.vbak` AS PED ON
	NF.PSTDAT = PED.AUDAT AND
	NF.PARID = PED.KUNNR AND 
	NF.BUKRS = PED.VKORG AND
	NF.NFTOT = PED.NETWR 
INNER JOIN 
	`production-servers-magnumtires.prdmgm_sap_cdc_processed.vbap` AS ITEM ON 
	PED.MANDT = ITEM.MANDT AND 
	PED.VBELN = ITEM.VBELN
INNER JOIN 
	`production-servers-magnumtires.prdmgm_sap_cdc_processed.but0id` AS RELV ON 
	PED.MANDT = RELV.CLIENT AND
	RELV.IDNUMBER = ITEM.PERVE_ANA
INNER JOIN
	`production-servers-magnumtires.prdmgm_sap_cdc_processed.but000` AS VEND ON
	PED.MANDT = VEND.CLIENT AND 
	RELV.PARTNER = VEND.PARTNER
WHERE 
	NF.MANDT = '300' AND
	NF.PARTYP = 'C' AND
	NF.PSTDAT BETWEEN '20230801' AND '20230831' AND
	NF.PARID > '1000000000' AND
	NF.DIRECT = '2' AND
	NF.CANCEL = '' AND
	NF.NAME1 NOT LIKE '%Cliente OTC%' AND
	NF.NAME1 NOT LIKE '%CLIENTE OTC%' AND
	NF.NAME1 NOT LIKE '%CLIENTE  OTC% - 3002'