SELECT 
	NF.MANDT,
	NF.BUKRS AS 'EMPRESA',
	LEFT(NF.BUKRS, 2) + RIGHT(NF.BRANCH, 2) AS 'CENTRO',
	NF.PSTDAT AS 'DATA_LÇTO',
	NF.PARTYP AS 'TIPO_PARCEIRO',
	NF.NFTYPE AS 'TIPO_NF',
	NF.NFENUM AS 'NUM_NF',
	NF.DIRECT AS 'DIRECAO',
	NF.CANCEL AS 'ESTORNO',
	NF.NFTOT AS 'MONTANTE'
FROM
	`production-servers-magnumtires.prdmgm_sap_cdc_processed.j_1bnfdoc` AS NF
WHERE
	NF.PSTDAT BETWEEN '2024-01-01' AND '2024-06-30' AND
	NF.PARTYP = 'C' AND
	NF.DIRECT = '2' AND
	NF.CANCEL = ''
ORDER BY
	LEFT(NF.BUKRS, 2) + RIGHT(NF.BRANCH, 2)	