SELECT 
	EST.MANDT, 
	EST.BUKRS AS 'EMPRESA', 
	EST.WERKS AS 'CENTRO', 
	EST.BUDAT_MKPF AS 'DATA',
	EST.LGORT AS 'DEPOSITO',
	EST.MBLNR AS 'DOC_MATERIAL',
	RIGHT(EST.MATNR, 6) AS 'MATERIAL',
	EST.BWART AS 'TIPO_MOV',
	EST.SHKZG AS 'D/C', 
	EST.MENGE AS 'QTD',
	EST.SALK3 AS 'MONTANTE', 
	EST.USNAM_MKPF AS 'USUARIO'
FROM 
	`production-servers-magnumtires.prdmgm_sap_cdc_processed.ndsm_v_mseg AS EST
WHERE 
	EST.MANDT = '300' AND 
	EST.BUDAT_MKPF BETWEEN '2024-06-01' AND '2024-06-30' AND
	EST.LGORT = ''