SELECT DISTINCT
  FIN.BUKRS AS EMPRESA,
  FIN.KUNNR AS ID_EXTERNO,
  FIN.BELNR AS DOC_CONTABIL,
  FIN.BUZEI AS ITEM_CONTABIL,
  FIN.DMBTR AS VALOR_TIT,
  FIN.SGTXT AS DESCRICAO,
  FIN.H_BLART AS COD_TIPO_DOCUMENTO_CONTABIL,
  CDHDR.CHANGENR AS DOC_ALTERACAO,
  CDHDR.USERNAME AS USUARIO,
  CDPOS.VALUE_OLD AS VALOR_ANTIGO,
  CDPOS.VALUE_NEW AS VALOR_NOVO,
  CDHDR.UDATE AS DT_ALTERACAO,
  CDHDR.TCODE AS TRANSACAO,
  CDHDR.CHANGE_IND AS TP_MODIF,
  CASE 
    WHEN CDHDR.CHANGE_IND = 'U' THEN 'ATUALIZACAO' 
    WHEN CDHDR.CHANGE_IND = 'I' THEN 'INSERIDO' 
    WHEN CDHDR.CHANGE_IND = 'D' THEN 'DELETADO' 
  END AS TP_ALTERACAO, 
  CDPOS.FNAME AS CAMPO_ALTERADO,
  'TIPO DE DOCUMENTO CONTÁBIL' AS DESCRICAO_CAMPO,
  FIN.BUPLA AS LOCAL_NEG,
  FIN.H_BUDAT AS DT_LANCAMENTO,
  FIN.AUGDT AS DT_COMPENSACAO,
  FIN.NETDT AS DT_VENCIMENTO,
  FIN.ZLSCH AS FORM_PAG
FROM		
  `production-servers-magnumtires.prdmgm_sap_cdc_processed.bseg` AS FIN
INNER JOIN 
  `production-servers-magnumtires.prdmgm_sap_cdc_processed.cdpos` AS CDPOS 
  ON CONCAT(FIN.BUKRS, FIN.BELNR, FIN.GJAHR, FIN.BUZEI) = RIGHT(CDPOS.TABKEY, 21)
  AND CDPOS.FNAME = 'H_BLART'  -- Garante que a mudança seja no campo de Tipo de Documento Contábil
  AND CDPOS.VALUE_OLD = 'DX' 
  AND CDPOS.VALUE_NEW = 'DB'
INNER JOIN
  `production-servers-magnumtires.prdmgm_sap_cdc_processed.cdhdr` AS CDHDR 
  ON CDHDR.CHANGENR = CDPOS.CHANGENR
WHERE
  FIN.H_BUDAT BETWEEN '2025-01-01' AND '2025-01-31'
ORDER BY 
  CDHDR.UDATE DESC;