SELECT DISTINCT 
  B.BUKRS AS Empresa,
  B.LIFNR AS ID_Fornecedor, 
  F.NAME1 AS Fornecedor, 
  EXTRACT(YEAR FROM B.H_BUDAT) AS Ano,
  B.H_BUDAT AS DT_Lancamento,
  B.BELNR AS Documento,
  FORMAT_DATE('%d/%m/%Y', DATE_ADD(B.ZFBDT, INTERVAL CAST(B.ZBD1T AS INT64) DAY)) AS Data_Vencimento,
  FORMAT_DATE('%d/%m/%Y', CURRENT_DATE()) AS Data_Hoje,
  DATE_DIFF(CURRENT_DATE(), DATE_ADD(B.ZFBDT, INTERVAL CAST(B.ZBD1T AS INT64) DAY), DAY) AS Diferenca_Dias,
  CASE
    WHEN DATE_DIFF(CURRENT_DATE(), DATE_ADD(B.ZFBDT, INTERVAL CAST(B.ZBD1T AS INT64) DAY), DAY) <= 30 THEN '1 a 30 Dias' 
    WHEN DATE_DIFF(CURRENT_DATE(), DATE_ADD(B.ZFBDT, INTERVAL CAST(B.ZBD1T AS INT64) DAY), DAY) BETWEEN 31 AND 60 THEN '31 a 60 dias'
    WHEN DATE_DIFF(CURRENT_DATE(), DATE_ADD(B.ZFBDT, INTERVAL CAST(B.ZBD1T AS INT64) DAY), DAY) BETWEEN 61 AND 90 THEN '61 a 90 dias'
    WHEN DATE_DIFF(CURRENT_DATE(), DATE_ADD(B.ZFBDT, INTERVAL CAST(B.ZBD1T AS INT64) DAY), DAY) BETWEEN 91 AND 120 THEN '91 a 120 dias'
    WHEN DATE_DIFF(CURRENT_DATE(), DATE_ADD(B.ZFBDT, INTERVAL CAST(B.ZBD1T AS INT64) DAY), DAY) BETWEEN 121 AND 150 THEN '121 a 150 dias'
    WHEN DATE_DIFF(CURRENT_DATE(), DATE_ADD(B.ZFBDT, INTERVAL CAST(B.ZBD1T AS INT64) DAY), DAY) BETWEEN 151 AND 180 THEN '150 a 180 dias'
    WHEN DATE_DIFF(CURRENT_DATE(), DATE_ADD(B.ZFBDT, INTERVAL CAST(B.ZBD1T AS INT64) DAY), DAY) BETWEEN 181 AND 360 THEN '181 a 360 dias'
    ELSE '+360 dias'
  END AS Aging_List,
  B.AUGCP AS Data_Compensacao,   
  CASE
    WHEN B.SHKZG = 'S' THEN 'Debito'
    WHEN B.SHKZG = 'H' THEN 'Credito'
    ELSE 'Nao identificado'
  END AS Debito_Credito,
  B.BELNR as Lcto_ctb, 
  B.DMBTR as Montante,
  B.SGTXT as Texto
FROM 
  `production-servers-magnumtires.prdmgm_sap_cdc_processed.bseg` as B
INNER JOIN 
  `production-servers-magnumtires.prdmgm_sap_cdc_processed.lfa1` as F 
  ON B.MANDT = F.MANDT 
  AND B.LIFNR = F.LIFNR
WHERE 
  F.LAND1 <> 'BR'
  AND B.LIFNR > '1000000000' 
  AND B.SHKZG = 'S'
  AND B.AUGBL = ''  
  AND B.HKONT = '1010301003' -- Conta Contábil Fornecedores Internacionais
  AND DATE_DIFF(CURRENT_DATE(), DATE_ADD(B.ZFBDT, INTERVAL CAST(B.ZBD1T AS INT64) DAY), DAY) > 150 
ORDER BY
  B.H_BUDAT ASC