SELECT DISTINCT 
TOP 10 
	SD.BUKRS AS 'EMPRESA',
	SD.KUNNR AS 'COD_CLIENTE',
	SD.ZLSCH AS 'FRM_PGTO',
	SD.BLART AS 'TP_DOC',
	SD.BUDAT AS 'DT_LÇTO',
	SD.ZFBDT AS 'DT_PRAZO',
	DATEDIFF(DAY,(SD.BUDAT),  SD.ZFBDT) AS 'DIAS_DIF', 
	SD.DMBTR AS 'VLR_NF'
FROM 
	`production-servers-magnumtires.prdmgm_sap_cdc_processed.BSAD` AS SD
WHERE
	SD.BUKRS = '2000' AND
	DATEDIFF(DAY,(SD.BUDAT),  SD.ZFBDT) > 0 AND 
	SD.ZLSCH = 'E' AND 
	SD.BLART = 'DZ'