SELECT 
DISTINCT 
	AB.MANDT, 
	AB.BUKRS AS 'EMPRESA', 
	CONVERT(VARCHAR, GETDATE(), 103) AS 'DT_HOJE',
	AB.BUDAT AS 'DATA_LÇTO',
	AB.AUGDT AS 'DATA_COMPENSACAO',
	AB.ZBD1T AS 'DIAS', 
	CONVERT(VARCHAR, DATEADD(DAY, AB.ZBD1T, AB.BUDAT), 103) AS 'DT_VENCIMENTO',
	AB.SHKZG AS 'D/C', 
	AB.BSCHL AS 'CHAVE_LÇTO',
	AB.KUNNR AS 'ID_EXTERNO', 
	CAD.NAME1 AS 'NOME_CLIENTE', 
	AB.BELNR AS 'LÇTO_CONTÁBIL', 
	AB.ZLSCH AS 'FORMA_PGTO',
	AB.BLART AS 'TP_DOCUMENTO',
	AB.XBLNR AS 'REFEERENCIA', 
	AB.HKONT AS 'CTA_RAZÃO',
	AB.BUZEI AS 'PARCELA',
	AB.DMBTR AS 'MONTANTE' 
FROM 
	[SAPPS4300].[dbo].BSID AS AB
INNER JOIN 
	[SAPPS4300].[dbo].KNA1 AS CAD ON AB.MANDT = CAD.MANDT AND AB.KUNNR = CAD.KUNNR
WHERE
	AB.MANDT = '300' AND 
	AB.KUNNR BETWEEN '100000001' AND '5000000000' AND 
	AB.KUNNR NOT IN ('1000020903', '1000016271', '1000033486', '1000017583') AND 
	AB.ZLSCH = 'J' AND
	DATEDIFF(DAY, DATEADD(DAY, AB.ZBD1T, AB.BUDAT), GETDATE()) > 60 AND 
	AB.SHKZG = 'S' AND
	AB.BLART = 'RV'
ORDER BY 
	AB.BUKRS