SELECT DISTINCT 
  CLIENTE.BUKRS AS EMPRESA,
  CLIENTE.BUPLA AS LOC_NEG,
  EMPRESA.BUTXT AS NOME_EMPRESA,
  CLIENTE.GJAHR AS EXERCICIO,
  CLIENTE.BELNR AS DOC_CONTABIL,
  CLIENTE.BLART AS COD_TP_CONTABIL,
  USUARIO.USNAM AS USUARIO,
  USUARIO.BLDAT AS DT_DOCUMENTO,
  USUARIO.BUDAT AS DT_LANCAMENTO,
  CLIENTE.BUZEI AS ITEM_DOCUMENTO_CONTABIL,
  CLIENTE.KUNNR AS COD_CLIENTE,
  CAD_CLI.NAME1 AS CLIENTE,
  CLIENTE.SGTXT AS DESCRICAO,
  CLIENTE.DMBTR AS VALOR_CLIENTE,
  CLIENTE.AUGBL AS DOC_COMPENSACAO,
  CLIENTE.AUGDT AS DT_COMPENSACAO,
  RESULTADO.HKONT AS CONTA_RESULTADO,
  PLANO.TXT20 AS CONTA_RAZAO_RESULTADO,
  RESULTADO.DMBTR AS VALOR_RESULTADO
FROM	production-servers-magnumtires.prdmgm_sap_cdc_processed.bsad as CLIENTE
INNER JOIN production-servers-magnumtires.prdmgm_sap_cdc_processed.bseg as RESULTADO ON 
  RESULTADO.BELNR = CLIENTE.BELNR 
  AND RESULTADO.HKONT LIKE '3%' 
  AND RESULTADO.SHKZG = 'S'
INNER JOIN production-servers-magnumtires.prdmgm_sap_cdc_processed.bkpf as USUARIO ON
  USUARIO.BUKRS = CLIENTE.BUKRS
  AND CLIENTE.BELNR = USUARIO.BELNR
INNER JOIN production-servers-magnumtires.prdmgm_sap_cdc_processed.t001 as EMPRESA ON 
  EMPRESA.BUKRS = CLIENTE.BUKRS  
INNER JOIN production-servers-magnumtires.prdmgm_sap_cdc_processed.kna1 as CAD_CLI ON
  CAD_CLI.KUNNR =  CLIENTE.KUNNR
LEFT JOIN production-servers-magnumtires.prdmgm_sap_cdc_processed.skat as PLANO ON 
  PLANO.KTOPL = '1000'
  AND PLANO.SAKNR = RESULTADO.HKONT
WHERE 
  CLIENTE.AUGDT BETWEEN '2024-02-01' AND '2024-02-29'
  AND CLIENTE.HKONT = '1010201001'
  AND CLIENTE.SHKZG = 'H'
  AND CLIENTE.BLART = 'RV'