WITH SUB1 AS  (
SELECT 
  EMPRESA, 
  COD_CLIENTE, 
  CLIENTE,
  MIN(DT_CLIENTE_MIN) AS DT_CLIENTE_MIN,
  MAX(DT_CLIENTE_MIN) AS DT_CLIENTE_MAX, 
  SUM(QTD_CLI) as total_linhas,
  SUM(VALOR) AS VALOR

FROM(
  
  SELECT DISTINCT
    CLI.BUKRS AS EMPRESA,
    CLI.KUNNR AS COD_CLIENTE,
    CAD.NAME1 AS CLIENTE,
    CLI.NETDT  AS DT_CLIENTE_MIN,
    SUM(CLI.DMBTR) AS VALOR,
    COUNT(*) AS QTD_CLI
  FROM production-servers-magnumtires.prdmgm_sap_cdc_processed.bseg as CLI
  INNER JOIN production-servers-magnumtires.prdmgm_sap_cdc_processed.kna1 as CAD ON CAD.KUNNR = CLI.KUNNR
  WHERE 
    CLI.HKONT = '1010201001'
    AND CLI.SHKZG = 'S'
    AND CLI.NETDT < '2024-11-01'
    AND (CLI.AUGDT is null OR CLI.AUGDT > '2024-11-30')
    AND CLI.KOART = 'D'
    AND CLI.UMSKZ = ''
    AND CLI.ZLSCH = 'E'
--    AND CLI.KUNNR = '1000008182'
  GROUP BY 
    CLI.BUKRS,
    CLI.KUNNR ,
    CAD.NAME1 ,
    CLI.NETDT 
  ORDER BY
    CLI.KUNNR,
    CLI.BUKRS

)
GROUP BY 
  EMPRESA, 
  COD_CLIENTE, 
  CLIENTE
),
SUB2 AS (

SELECT 
  EMPRESA_FORN,
  COD_FORN,
  MIN(DT_FORN_MIN)DT_FORN_MIN,
  MAX(DT_FORN_MIN) AS DT_FORN_MAX,
  SUM(VLR_PG_fORFN) AS VLR_PG_FORN,
  SUM(QTD_FORN) AS QTD_FORN
FROM(

  SELECT DISTINCT
    FORN.BUKRS AS EMPRESA_FORN,
    FORN.LIFNR AS COD_FORN,
    FORN.AUGCP AS DT_FORN_MIN,
    SUM(FORN.DMBTR) AS VLR_PG_fORFN,
    COUNT(FORN.LIFNR) AS QTD_FORN
  FROM production-servers-magnumtires.prdmgm_sap_cdc_processed.bseg as FORN
  WHERE 
     FORN.HKONT IN( '2010101003','2010101004')
     AND FORN.SHKZG = 'H' 
     AND FORN.UMSKZ = '' 
     AND FORN.AUGDT BETWEEN '2024-12-01'AND '2024-12-31'
--     AND FORN.LIFNR = '1000008182'
  GROUP BY 
    FORN.BUKRS,
    FORN.LIFNR,
    FORN.AUGCP

)
GROUP BY 
  EMPRESA_FORN,
  COD_FORN

)

SELECT 
  EMPRESA, 
  COD_CLIENTE AS FORNECEDOR, 
  CLIENTE AS FORNECEDOR, 
  DT_CLIENTE_MIN,
  DT_CLIENTE_MAX,
  total_linhas AS QTD_TIT_INDIMPLENTES,
  VALOR AS VLR_TIT_INADIMPLENTES,
  SUB2.DT_FORN_MIN,
  SUB2.DT_FORN_MAX,
  SUB2.QTD_FORN,
  SUB2.VLR_PG_FORN
FROM SUB1 
JOIN SUB2 ON
    EMPRESA = EMPRESA_FORN AND 
  COD_CLIENTE = COD_FORN
  AND SUB2.DT_FORN_MAX > DT_CLIENTE_MIN