SELECT 
DISTINCT 
	FIN.BUKRS AS'EMPRESA',
	FAT.BUDAT AS 'DATA LANÇAMENTO',
	FIN.BELNR AS 'NUM DOC',
	FAT.BLART AS 'TP DOC',
	FIN.HKONT AS 'CTA RAZAO',
	FIN.BSCHL AS 'CHAVE LÇTO',
	FIN.SHKZG AS 'D/C',
	FAT.USNAM AS 'USUÁRIO',
	DOC.PARID AS 'CLIENTE',
	DOC.NFENUM AS 'NUM_NF', 
	DOC.NFTOT AS 'VLR NF'
FROM 
	[SAPPS4300].[dbo].BSEG AS FIN
INNER JOIN 
	[SAPPS4300].[dbo].BKPF AS FAT ON FIN.MANDT = FAT.MANDT AND FIN.BUKRS = FAT.BUKRS AND FIN.BELNR = FAT.BELNR
INNER JOIN 
	[SAPPS4300].[dbo].J_1BNFLIN AS LIN ON FAT.AWKEY = LIN.REFKEY
INNER JOIN 
	[SAPPS4300].[dbo].J_1BNFDOC AS DOC ON LIN.DOCNUM = DOC.DOCNUM
WHERE 
	FIN.MANDT = '300' AND 
	FAT.BUDAT BETWEEN '20231101' AND '20231130' AND 
	FIN.HKONT = '3010101001' AND 
	FIN.BSCHL = '40' AND
	USNAM <> 'JOB_USER' AND 
	DOC.PARID > '1000000000'