SELECT DISTINCT
	SD.MANDT,
	SD.BUKRS as EMPRESA,
	SD.KUNNR as ID_EXTERNO,
	CAD.NAME1 as NOME_CLIENTE,
	SD.BUDAT as DATA_LCTO,
	SD.AUGDT as DATA_COMPENSACAO,
	SD.AUGBL as DOC_COMPENSACAO,
	SD.BLART as TIPO_DOCUMENTO,
	SD.SHKZG as D_C,
	SD.SAKNR as CONTA_CONTABIL, 
	FAT.USNAM as USUARIO,
	SD.XBLNR as REF_NF,
	SD.BUZEI as PARCELA,
	CASE 
		WHEN SD.SHKZG = 'H' THEN SD.DMBTR * -1
		ELSE SD.DMBTR
	END AS VLR_PARCELA
FROM 
	`production-servers-magnumtires.prdmgm_sap_cdc_processed.bsad` as SD
INNER JOIN 
	`production-servers-magnumtires.prdmgm_sap_cdc_processed.bkpf` as FAT ON SD.BUKRS = FAT.BUKRS AND SD.GJAHR = FAT.GJAHR AND SD.BELNR = FAT.BELNR
INNER JOIN 
	`production-servers-magnumtires.prdmgm_sap_cdc_processed.kna1` as CAD ON SD.MANDT = CAD.MANDT AND SD.KUNNR = CAD.KUNNR 
WHERE
	SD.MANDT = '300' AND 
	SD.KUNNR > '1000000000' AND 
	SD.AUGDT BETWEEN '2023-01-01' AND '2023-11-30' AND
	SD.BLART = 'ES' AND
	FAT.USNAM <> 'JOB_USER'
ORDER BY
	CAD.NAME1
