SELECT DISTINCT 
  JUROS.BUKRS AS COD_EMPRESA,
  EMP.BUTXT AS EMPRESA,
  JUROS.HKONT AS CONTA_RAZAO,
  JUROS.ZUONR AS ATRIBUICAO,
  JUROS.BELNR AS DOC_PG,
  JUROS.H_BUDAT AS DT_LANC,
  JUROS.H_BLART AS COD_TP,
  F.LIFNR AS COD_FORNECEDOR,
  FORN.NAME1 AS FORNECEDOR,
  PG.BUZEI AS ITEM_DOCUMENTO,
  PG.SGTXT AS DESCRICAO_DOC,
  F.NETDT AS VENCIMENTO,
  PG.AUGCP AS DT_COMPENSACAO,
  DATE_DIFF(F.NETDT, PG.AUGCP, DAY) AS DIAS_ATRASO,
  PG.DMBTR AS VALOR_DOCUMENTO,
  JUROS.DMBTR AS VALOR_JUROS
FROM
  production-servers-magnumtires.prdmgm_sap_cdc_processed.bseg AS JUROS
INNER JOIN 
  production-servers-magnumtires.prdmgm_sap_cdc_processed.bseg AS F
  ON F.BELNR = JUROS.BELNR
  AND F.GJAHR = JUROS.GJAHR
  AND F.BUKRS = JUROS.BUKRS
  AND F.KOART = 'K'
  AND F.SHKZG = 'S'
INNER JOIN 
  `production-servers-magnumtires.prdmgm_sap_cdc_processed.bseg` as PG
    ON JUROS.BUKRS = PG.BUKRS 
    AND PG.SHKZG = 'H' 
    AND JUROS.BELNR = PG.BELNR 
    AND PG.HKONT LIKE '10101026%' 
    AND JUROS.GJAHR = PG.GJAHR  
INNER JOIN
  production-servers-magnumtires.prdmgm_sap_cdc_processed.t001 AS EMP
    ON JUROS.BUKRS = EMP.BUKRS
INNER JOIN 
  production-servers-magnumtires.prdmgm_sap_cdc_processed.lfa1 AS FORN
    ON F.LIFNR = FORN.LIFNR
WHERE 
  JUROS.HKONT IN ('3040302001', '3040302011')
  AND JUROS.SHKZG = 'S' 
  AND JUROS.KOART = 'S'
  AND JUROS.H_BUDAT BETWEEN '2024-12-01' AND '2024-12-31'
--  AND DATE_DIFF(FIN.AUGCP, FIN.NETDT, DAY) < 0
