WITH base AS (
  SELECT DISTINCT
    FIN.BUKRS AS COD_EMPRESA,
    FIN.BUPLA AS LOCAL_NEG,
    EMP.BUTXT AS EMPRESA,
    FIN.KUNNR AS COD_CLIENTE,
    CLI.NAME1 AS CLIENTE,
    FIN.BELNR AS DOC_CONTABIL,
    FIN.BUZEI AS ITEM_CONTABIL,
    FIN.DMBTR AS VALOR_TIT,
    FIN.SGTXT AS DESCRICAO,
    FIN.H_BLART AS COD_TIPO_DOCUMENTO_CONTABIL,
    CDHDR.CHANGENR AS DOC_ALTERACAO,
    CDHDR.USERNAME AS USUARIO,

    SAFE.PARSE_DATE('%Y%m%d', NULLIF(TRIM(CDPOS.VALUE_OLD), '')) AS VENCIMENTO_ANTIGO_DT,
    SAFE.PARSE_DATE('%Y%m%d', NULLIF(TRIM(CDPOS.VALUE_NEW), '')) AS VENCIMENTO_NOVO_DT,

    CDHDR.UDATE AS DT_ALTERACAO,
    CDHDR.TCODE AS TRANSACAO,
    CDHDR.CHANGE_IND AS TP_MODIF,
    CASE 
      WHEN CDHDR.CHANGE_IND = 'U' THEN 'ATUALIZACAO' 
      WHEN CDHDR.CHANGE_IND = 'I' THEN 'INSERIDO' 
      WHEN CDHDR.CHANGE_IND = 'D' THEN 'DELETADO' 
    END AS TP_ALTERACAO,
    CDPOS.FNAME AS CAMPO_ALTERADO,
    'DATA BASE PARA PAGAMENTO' AS DESCRICAO_CAMPO,
    FIN.H_BUDAT AS DT_LANCAMENTO,
    FIN.AUGDT AS DT_COMPENSACAO,
    FIN.NETDT AS DT_VENCIMENTO,
    FIN.ZLSCH AS FORM_PAG,
    VEN.CNAME AS VENDEDOR
  FROM
    `production-servers-magnumtires.prdmgm_sap_cdc_processed.bseg` AS FIN
  INNER JOIN
    `production-servers-magnumtires.prdmgm_sap_cdc_processed.cdpos` AS CDPOS
      ON CONCAT(FIN.BUKRS, FIN.BELNR, FIN.GJAHR, FIN.BUZEI) = RIGHT(CDPOS.TABKEY, 21)
  INNER JOIN
    `production-servers-magnumtires.prdmgm_sap_cdc_processed.cdhdr` AS CDHDR
      ON CDHDR.CHANGENR = CDPOS.CHANGENR
  INNER JOIN
    `production-servers-magnumtires.prdmgm_sap_cdc_processed.t001` AS EMP
      ON EMP.BUKRS = FIN.BUKRS
  INNER JOIN
    `production-servers-magnumtires.prdmgm_sap_cdc_processed.kna1` AS CLI
      ON CLI.KUNNR = FIN.KUNNR
  INNER JOIN
    `Portal_do_Vendedor.Clientes_x_Vendedores` AS VEN
      ON CLI.KUNNR = VEN.KUNNR
  WHERE
    FIN.SHKZG = 'S'
    AND CDPOS.FNAME = 'ZFBDT'
    AND CDPOS.TABNAME = 'BSEG'
    AND CDHDR.UDATE BETWEEN '2026-06-01' AND '2026-06-30'
)

SELECT
  COD_EMPRESA,
  LOCAL_NEG,
  EMPRESA,
  COD_CLIENTE,
  CLIENTE,
  DOC_CONTABIL,
  ITEM_CONTABIL,
  VALOR_TIT,
  DESCRICAO,
  COD_TIPO_DOCUMENTO_CONTABIL,
  DOC_ALTERACAO,
  USUARIO,
  FORMAT_DATE('%d/%m/%Y', VENCIMENTO_ANTIGO_DT) AS VENCIMENTO_ANTIGO,
  FORMAT_DATE('%d/%m/%Y', VENCIMENTO_NOVO_DT) AS VENCIMENTO_NOVO,
  DATE_DIFF(VENCIMENTO_NOVO_DT, VENCIMENTO_ANTIGO_DT, DAY) AS DIF_DIAS,
  DT_ALTERACAO,
  TRANSACAO,
  TP_MODIF,
  TP_ALTERACAO,
  CAMPO_ALTERADO,
  DESCRICAO_CAMPO,
  DT_LANCAMENTO,
  DT_COMPENSACAO,
  DT_VENCIMENTO,
  FORM_PAG,
  VENDEDOR
FROM base
WHERE DATE_DIFF(VENCIMENTO_NOVO_DT, VENCIMENTO_ANTIGO_DT, DAY) < 0;
